In [150]:
import pandas as pd
import numpy as np

In [151]:
df=pd.read_csv('CarPrice.csv')

In [152]:
df.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [153]:
x=df.iloc[:,[1,9,10,11,12,13,16,18,19,20,21,22,23,24]].values

In [154]:
y=df.iloc[:,25].values

In [155]:
x


array([[ 3.000e+00,  8.860e+01,  1.688e+02, ...,  5.000e+03,  2.100e+01,
         2.700e+01],
       [ 3.000e+00,  8.860e+01,  1.688e+02, ...,  5.000e+03,  2.100e+01,
         2.700e+01],
       [ 1.000e+00,  9.450e+01,  1.712e+02, ...,  5.000e+03,  1.900e+01,
         2.600e+01],
       ...,
       [-1.000e+00,  1.091e+02,  1.888e+02, ...,  5.500e+03,  1.800e+01,
         2.300e+01],
       [-1.000e+00,  1.091e+02,  1.888e+02, ...,  4.800e+03,  2.600e+01,
         2.700e+01],
       [-1.000e+00,  1.091e+02,  1.888e+02, ...,  5.400e+03,  1.900e+01,
         2.500e+01]])

In [156]:
y

array([13495.   , 16500.   , 16500.   , 13950.   , 17450.   , 15250.   ,
       17710.   , 18920.   , 23875.   , 17859.167, 16430.   , 16925.   ,
       20970.   , 21105.   , 24565.   , 30760.   , 41315.   , 36880.   ,
        5151.   ,  6295.   ,  6575.   ,  5572.   ,  6377.   ,  7957.   ,
        6229.   ,  6692.   ,  7609.   ,  8558.   ,  8921.   , 12964.   ,
        6479.   ,  6855.   ,  5399.   ,  6529.   ,  7129.   ,  7295.   ,
        7295.   ,  7895.   ,  9095.   ,  8845.   , 10295.   , 12945.   ,
       10345.   ,  6785.   ,  8916.5  ,  8916.5  , 11048.   , 32250.   ,
       35550.   , 36000.   ,  5195.   ,  6095.   ,  6795.   ,  6695.   ,
        7395.   , 10945.   , 11845.   , 13645.   , 15645.   ,  8845.   ,
        8495.   , 10595.   , 10245.   , 10795.   , 11245.   , 18280.   ,
       18344.   , 25552.   , 28248.   , 28176.   , 31600.   , 34184.   ,
       35056.   , 40960.   , 45400.   , 16503.   ,  5389.   ,  6189.   ,
        6669.   ,  7689.   ,  9959.   ,  8499.   , 

In [157]:

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [158]:
len(x_train)

164

In [159]:
len(x_test)

41

In [160]:
from sklearn.linear_model import LinearRegression
Regressor=LinearRegression()
Regressor.fit(x_train,y_train)
Y_pred=Regressor.predict(x_test)


In [161]:
Y_pred

array([39587.44013643,  6513.35251035, 10174.724844  , 13516.55207526,
        6718.41540524, 16776.25339643,  4879.24059787,  9810.2331489 ,
        6915.33297758,  9133.17908338, 15888.55232174, 17415.37272517,
        7627.4177682 ,  6304.07247866, 13964.78917954, 10788.20473743,
       10886.76402782, 51932.88384372, 20721.96501875, 16804.12916744,
        7600.60400446,  8850.87734053, 15862.43481709, 25322.3475047 ,
        8903.29123418, 13630.83643759,  8841.68510824, 15525.25573545,
       15674.1074793 , 24386.6456066 ,  6207.65482085,  7872.96128724,
       19461.69883313,  9588.78555756,  7702.84912444, 16150.81161434,
       22833.42647175,  6330.37816197,  2821.4378271 ,  6945.48531621,
        5976.52617151])

In [162]:
from sklearn.metrics import r2_score
print(r2_score(Y_pred,y_test))


0.8219806984225227


In [166]:
print("car price of such features is:",Regressor.predict([[3,88.6,168.8,64.1,48.8,2548,130,3.47,2.68,9,111,5000,21,27]])[0])

car price of such features is: 13688.912961551672
